# -*- coding: utf-8 -*-
"""Wordcloud-g2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173SBpkhBjJ4-U53_fxJ0eynRsbZI9nyA
"""

# exercice 1
# Armand
# state: ongoing

# exercice 2
# Guillaume
# state: ongoing

# exercice 3
# Elodie
# state: ongoing