# -*- coding: utf-8 -*-
"""Wordcloud-g2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173SBpkhBjJ4-U53_fxJ0eynRsbZI9nyA
"""

# exercice 1
# Armand
# state: ongoing

# exercice 2
# Guillaume
# state: ongoing
!pip install pillow
import numpy as np 
from PIL import Image,ImageOps
import matplotlib.pyplot as plt
from wordcloud import WordCloud,STOPWORDS,ImageColorGenerator
from scipy.ndimage import gaussian_gradient_magnitude 

# Download the Shakespeare text from the desktop
file=open('romeo.txt')
text=file.read()

# Create the WordCloud
canvas_width=1920
canvas_height=1080 

# Generate wordcloud
wordcloud = WordCloud(width=canvas_width,height=canvas_height).generate(text)
wordcloud.to_file("simple_wordcloud.png") 
plt.figure(figsize = (10, 10), facecolor=None)

# Save the output wordcloud in png format
plt.imshow(wordcloud, interpolation='bilinear')

# Show the image output 
plt.axis("off") 
plt.tight_layout(pad = 0)
plt.show() 

#--------additional tricks----
# By default wordcloud generates random patterns but you can fix the seed
# Generate wordcloud
# Replace 1 with any number to get different result
canvas_width=1920
canvas_height=1080 
wordcloud = WordCloud(width=canvas_width,height=canvas_height).generate(text)
wordcloud = WordCloud(random_state=1).generate(text) 
wordcloud.to_file("simple_wordcloud.png") 
plt.figure(figsize = (10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off") 
plt.tight_layout(pad = 0)
plt.show() 
# exercice 3
# Elodie
# state: ongoing

# Exercice 3--------------------------------------------------------------------
# White font and excluding the word THY
canvas_width=1920
canvas_height=1080 
wordcloud = WordCloud(width=canvas_width,height=canvas_height).generate(text)
stopwords = set(STOPWORDS)
stopwords.add("thy")
wordcloud = WordCloud(stopwords=stopwords,background_color='white',random_state=1,colormap='hot',max_font_size=800,min_font_size=20,width=canvas_width,height=canvas_height).generate(text)
wordcloud.to_file("simple_wordcloud.png") 
plt.figure(figsize = (10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off") 
plt.tight_layout(pad = 0)
plt.show() 
